Web/ViewModels/NewsletterViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace Total.ToolAcademy.Web.ViewModels
{
    public class SignupFormViewModel
    {
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a valid email address")]
        [StringLength(256, ErrorMessage = "Please enter a valid email address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        [Display(Name = "Email Address")]
        public string Address { get; set; }
    }
}

Web/Controllers/Default/NewsletterController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using Castle.Core.Logging;
using Total.ToolAcademy.Entity;
using Total.ToolAcademy.Framework;
using Total.ToolAcademy.Helpers;
using Total.ToolAcademy.Web.ViewModels;

namespace Total.ToolAcademy.Web.Controllers
{
    public class NewsletterController : Controller
    {
        public ILogger Logger { get; set; }

        private readonly IDbContext _context;

        public NewsletterController(IDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Signup(SignupFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var address = model.Address.ToLower();
            if (!address.IsValidEmail())
            {
                ModelState.AddModelError("Address", "Please enter a valid email address.");
                return View(model);
            }

            var exists = await _context.MailingLists.AnyAsync(e => e.EmailAddress == address);
            if (exists)
            {
                ModelState.AddModelError(string.Empty, "Thank you, but you have already signed up for our newsletter!");
                return View(model);
            }

            _context.MailingLists.Add(new MailingList { EmailAddress = address });
            await _context.SaveChangesAsync();

            Logger.InfoFormat("Newsletter signup: {0}", address);

            return Redirect("~/thank-you-newsletter");
        }
    }
}

Web/Views/Newsletter/Signup.cshtml
@model SignupFormViewModel

@{
    ViewBag.Title = "Signup to our Newsletter";
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

<div class="container">
    <h2 class="page-header text-center">Join Our Mailing List for the Latest News &amp; Offers</h2>
    @using (Html.BeginForm("Signup", "Newsletter", new { area = string.Empty }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-md-3">
                <div class="form-group@(ViewData.ModelState.HasError("Name") ? " has-error" : "")">
                    @Html.LabelFor(m => m.Name, new { @class = "control-label sr-only" })
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Your name" })
                </div><!-- /form-group -->
            </div><!-- /col-md-3 -->
            <div class="col-md-6">
                <div class="form-group@(ViewData.ModelState.HasError("Address") ? " has-error" : "")">
                    @Html.LabelFor(m => m.Address, new { @class = "control-label sr-only" })
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Your email address" })
                    @Html.ValidationMessageFor(m => m.Address, null, new { @class = "help-block" })
                </div><!-- /form-group -->
            </div><!-- /col-md-6 -->
            <div class="col-md-3">
                <button type="submit" class="btn btn-inverse btn-block">Subscribe</button>
            </div><!-- /col-md-3 -->
        </div><!-- /row -->
    }
</div><!-- /container -->

Web/Views/Newsletter/_SignupFooter.cshtml
@model SignupFormViewModel
<div class="bg-loblolly">
    <div class="signup-form container">
        <h2>Join Our Mailing List for the Latest News &amp; Offers</h2>
    @using (Html.BeginForm("Signup", "Newsletter", new { area = string.Empty }, FormMethod.Post)) {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "control-label sr-only" })
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Your name" })
                </div><!-- /form-group -->
            </div><!-- /col-md-3 -->
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Address, new { @class = "control-label sr-only" })
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Your email address" })
                </div><!-- /form-group -->
            </div><!-- /col-md-6 -->
            <div class="col-md-3">
                <button type="submit" class="btn btn-inverse btn-block">Subscribe</button>
            </div><!-- /col-md-3 -->
        </div><!-- /row -->
    }
    </div><!-- /signup-form container -->
</div><!-- /bg-loblolly -->