Web/Controllers/Default/SearchController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Total.ToolAcademy.Web.ViewModels;

namespace Total.ToolAcademy.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly List<int> _validCounts = new List<int>
        {
            8, 16, 32, 64
        }; 

        //[OutputCache(Duration = 900, VaryByParam = "q;page;count")]
        // GET: /search/?q={phrase}
        public ActionResult Index(string q, int page = 1, int count = 8)
        {
            var phrase = q.ToLower();
            ViewBag.SearchPhrase = phrase;

            if (!_validCounts.Contains(count))
                count = 8;
            
            return View(new SearchViewModel
            {
                Phrase = phrase,
                Page = page,
                Count = count,
                ValidCounts = _validCounts
            });
        }
    }
}

Web/Views/Shared/GenericError.cshtml
@model HandleErrorInfo
@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

<div class="container">
    <h1>Error</h1>
    <p>An error occurred while processing your request.</p>
</div><!-- /container -->

Web/Views/Shared/_DefaultLayout.cshtml
<!doctype html>
<html class="no-js" lang="en-gb">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@ViewBag.Title | The Tool Academy</title>
        <meta name="description" content="@ViewBag.Description"/>
        <meta name="viewport" content="width=device-width" />
        
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,400italic,600,700' rel='stylesheet' type='text/css'>
        
        @Styles.Render("~/css/bootstrap", "~/css/font-awesome", "~/css/main")
        @RenderSection("HeaderScripts", false)
        <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        @Scripts.Render("~/js/modernizr")
    </head>
    <body>
        
        <div class="page">
            <header class="site-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="site-logo"><a href="~/" title="The Tool Academy"><img src="~/assets/img/tool-academy-logo.jpg" alt="The Tool Academy" class="img-responsive" /></a></h1>
                        </div><!-- /col-md-6 -->
                        <div class="col-md-3">
                            <p>Freephone Orderline</p>
                            <h2 class="text-smalt">0808 1682 447</h2>
                        </div><!-- /col-md-3 -->
                        <div class="col-md-3">
                            @Html.Partial("~/Views/Basket/_BasketOverview.cshtml", ViewBag.Basket as BasketOverviewViewModel)
                        </div><!-- /col-md-3 -->
                    </div><!-- /row -->
                </div><!-- /container -->
            
                <nav class="bg-smalt" role="navigation">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 pull-right">
                            @using (Html.BeginForm("Index", "Search", new { area = string.Empty }, FormMethod.Get)) {
                                <div class="input-group">
                                    @Html.TextBox("q", ViewBag.SearchPhrase as string, new { @class = "form-control" })
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                                    </span>
                                </div><!-- /input-group -->
                            }
                            </div><!-- /col-md-6 pull-right -->
                            <div class="col-md-6">
                                @Html.Partial("~/Views/Navigation/_MainNavigation.cshtml", ViewBag.MainNavigation as MainNavigationViewModel)
                            </div><!-- /col-md-6 -->
                        </div><!-- /row -->
                    </div><!-- /container-->
                </nav><!-- /bg-smalt -->
            </header><!-- /site-header -->
        
            <div class="site-content">
                @RenderBody()
            </div><!-- /site-content -->
        </div><!-- /page -->
        
        <footer class="site-footer">
            <div class="bg-fun-blue">
                <div class="site-info container">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <h2>Contact Us</h2>
                            <p class="md-margin-bottom">Freephone Orderline <br />0808 1682 447</p>
                            <p>Technical <br />01623 555 512 Ext. 5</p>
                        </div><!-- /col-md-4 -->
                        <div class="col-md-4 text-center">
                            <h2>Orders</h2>
                        </div><!-- /col-md-4 -->
                        <div class="col-md-4 text-center">
                            <h2>Quick Links</h2>
                        </div><!-- /col-md-4 -->
                    </div><!-- /row -->
                    <div class="row">
                        <div class="col-md-4">
                            <h2 class="text-center">Shop Opening Hours</h2>
                            <dl class="dl-horizontal">
                                <dt>Mon to Fri</dt>
                                <dd>8am to 6pm</dd>
                                <dt>Sat</dt>
                                <dd>8am to 1pm</dd>
                            </dl><!-- /dl-horizontal -->
                            
                            <h2 class="lg-margin-top text-center">Stay Connected</h2>
                            <p class="text-center"><a href="#"><i class="fa fa-facebook-square"></i></a> <a href="#"><i class="fa fa-twitter"></i></a></p>
                        </div><!-- /col-md-4 -->
                        <div class="col-md-4 text-center">
                            <h2>Small Print</h2>
                        </div><!-- /col-md-4 -->
                        <div class="col-md-4 text-center">
                            <h2>Essential Products</h2>
                        </div><!-- /col-md-4 -->
                    </div><!-- /row -->
                </div><!-- /site-info container text-center -->
            </div><!-- /bg-fun-blue -->
        
            @Html.Partial("~/Views/Newsletter/_SignupFooter.cshtml", new SignupFormViewModel())
        
            <div class="bg-pickled-bluewood">
                <div class="site-colophon container">
                    <div class="row">
                        <div class="col-md-6">
                            <p>&copy; @DateTime.Now.Year Tool Academy Ltd. All rights reserved.</p>
                        </div><!-- /col-md-6 -->
                        <div class="col-md-6 text-right">
                            <p><a href="http://www.totalsolutions.co.uk/website-development/">Website Designed &amp; Built by Total Solutions IT Group Ltd.</a></p>
                        </div><!-- /col-md-6 text-right -->
                    </div><!-- /row -->
                </div><!-- /site-colophon container -->
            </div><!-- /bg-pickled-bluewood -->
        </footer><!-- /site-footer -->
        
        @Scripts.Render("~/js/jquery", "~/js/bootstrap", "~/js/plugins")
        @RenderSection("FooterScripts", false)
        @Scripts.Render("~/js/main")
    </body>
</html>

Web/Views/Shared/_Loader.cshtml
<img src="~/assets/img/all/loader.gif" alt="Loader" class="loader loader-fallback" />
<div class="loader center-block">
    <span class="left"><span class="anim"></span></span>
    <span class="right"><span class="anim"></span></span>
</div><!-- /loader center-block -->